# Generated by Django 4.2.5 on 2023-12-20 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientNote",
            new_name="ClientMainNote",
        ),
        migrations.AlterModelOptions(
            name="clientmonthlynote",
            options={
                "verbose_name": "Заметка о клиенте по месяцам",
                "verbose_name_plural": "Заметки о клиентах по месяцам",
            },
        ),
        migrations.AlterUniqueTogether(
            name="clientmonthlynote",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="clientmonthlynote",
            name="general",
            field=models.TextField(blank=True, null=True, verbose_name="Общее"),
        ),
        migrations.AddField(
            model_name="clientmonthlynote",
            name="measurements",
            field=models.TextField(blank=True, null=True, verbose_name="Измерения"),
        ),
        migrations.AddField(
            model_name="clientmonthlynote",
            name="nutrition",
            field=models.TextField(blank=True, null=True, verbose_name="Питание"),
        ),
        migrations.AddField(
            model_name="clientmonthlynote",
            name="workout",
            field=models.TextField(blank=True, null=True, verbose_name="Тренировки"),
        ),
        migrations.AlterField(
            model_name="clientmonthlynote",
            name="month",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Январь"),
                    (2, "Февраль"),
                    (3, "Март"),
                    (4, "Апрель"),
                    (5, "Май"),
                    (6, "Июнь"),
                    (7, "Июль"),
                    (8, "Август"),
                    (9, "Сентябрь"),
                    (10, "Октябрь"),
                    (11, "Ноябрь"),
                    (12, "Декабрь"),
                ],
                default=1,
                verbose_name="Месяц",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientmonthlynote",
            unique_together={("client", "month", "year")},
        ),
        migrations.RemoveField(
            model_name="clientmonthlynote",
            name="text",
        ),
        migrations.RemoveField(
            model_name="clientmonthlynote",
            name="topic",
        ),
    ]
