# Generated by Django 4.2.5 on 2023-12-25 09:39

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=users.models.avatars_path,
                verbose_name="Аватар",
            ),
        ),
    ]
