# Generated by Django 4.2.5 on 2023-12-06 14:34

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar_user_birthday_user_height_user_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.avatars_path,
                verbose_name="Аватар",
            ),
        ),
    ]
