# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anthropometry", "0002_remove_anthropometry_photo_access_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anthropometry",
            options={
                "get_latest_by": "date",
                "ordering": ["-date"],
                "verbose_name": "Антропометрия",
                "verbose_name_plural": "Антропометрии",
            },
        ),
        migrations.AlterModelOptions(
            name="anthropometryphotoaccess",
            options={
                "verbose_name": "Доступ к фото",
                "verbose_name_plural": "Доступы к фото",
            },
        ),
    ]
