# Generated by Django 4.1 on 2023-05-02 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetQuestionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата заполнения",
                        verbose_name="Дата заполнения",
                    ),
                ),
                (
                    "date_update",
                    models.DateField(
                        auto_now=True,
                        help_text="Дата последнего редактирования",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Мужской"),
                            ("F", "Женский"),
                            ("?", "Свой вариант"),
                        ],
                        max_length=1,
                        verbose_name="Биологический пол",
                    ),
                ),
                (
                    "sex_comment",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Прокомментируйте свой ответ",
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(verbose_name="Рост"),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        verbose_name="Текущий вес"
                    ),
                ),
                (
                    "weight_min",
                    models.PositiveSmallIntegerField(
                        verbose_name="Минимальный вес за последние 5 лет"
                    ),
                ),
                (
                    "weight_max",
                    models.PositiveSmallIntegerField(
                        verbose_name="Максимальный вес за последние 5 лет"
                    ),
                ),
                (
                    "weight_avg",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="указывайте, если вам сейчас 30 лет и более",
                        null=True,
                        verbose_name="Средний вес между 20-25 годами",
                    ),
                ),
                (
                    "daily_steps",
                    models.CharField(
                        max_length=255,
                        verbose_name="Среднее количество шагов в сутки",
                    ),
                ),
                (
                    "sleep_time",
                    models.CharField(
                        max_length=255, verbose_name="Время укладывания ко сну"
                    ),
                ),
                (
                    "wakeup_time",
                    models.CharField(
                        max_length=255,
                        verbose_name="Время вставания после сна",
                    ),
                ),
                (
                    "sleep_problems",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Как часто нарушается и на какое время",
                    ),
                ),
                (
                    "daily_meals_amount",
                    models.CharField(
                        max_length=255,
                        verbose_name="Количество полноценных приёмов пищи в сутки",
                    ),
                ),
                (
                    "daily_snacks_amount",
                    models.CharField(
                        max_length=255,
                        verbose_name="Количество перекусов в сутки",
                    ),
                ),
                (
                    "common_meal",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы едите наиболее часто и регулярно"
                    ),
                ),
                (
                    "weekly_meal",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы едите примерно раз в неделю"
                    ),
                ),
                (
                    "yearly_meal",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы едите несколько раз в год"
                    ),
                ),
                (
                    "favorite_meal",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы считаете самой вкусной, желанной и любимой"
                    ),
                ),
                ("goal", models.TextField(verbose_name="Ваша цель")),
                (
                    "goal_mark",
                    models.TextField(
                        verbose_name="Какой показатель поможет нам эту цель измерить? (например, килограммы)"
                    ),
                ),
                (
                    "goal_attempts",
                    models.TextField(
                        verbose_name="Были ли ранее попытки достичь этой цели? Опишите их и назовите количество"
                    ),
                ),
                (
                    "goal_obstacle",
                    models.TextField(
                        verbose_name="Главные препятствия к достижению вашей цели"
                    ),
                ),
                (
                    "goal_importance",
                    models.PositiveSmallIntegerField(
                        verbose_name="Насколько важна указанная цель"
                    ),
                ),
                (
                    "goal_maxtime",
                    models.TextField(
                        verbose_name="Какое максимальное количество времени можно уделить достижению цели"
                    ),
                ),
                (
                    "readiness_to_change",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "Не вижу необходимости в серьёзных переменах, хочу лишь слегка скорректировать образ жизни.",
                            ),
                            (
                                "2",
                                "Готов к переменам в образе жизни, скоро начну их воплощать.",
                            ),
                            (
                                "3",
                                "Хочу изменить свой образ жизни, но не уверен, что смогу.",
                            ),
                            (
                                "4",
                                "Начал менять образ жизни в течение последнего полугода.",
                            ),
                            (
                                "5",
                                "Работаю над изменением образа жизни, но чувствую, что нуждаюсь в помощи, чтобы продвинуться дальше.",
                            ),
                            (
                                "6",
                                "Активно работаю над собой, продвигаюсь, но хочу делать это ещё лучше.",
                            ),
                        ],
                        max_length=1,
                        verbose_name="Готовность к изменениям",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета знакомства клиента",
                "verbose_name_plural": "Анкеты знакомства клиентов",
            },
        ),
        migrations.CreateModel(
            name="HealthQuestionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата заполнения",
                        verbose_name="Дата заполнения",
                    ),
                ),
                (
                    "date_update",
                    models.DateField(
                        auto_now=True,
                        help_text="Дата последнего редактирования",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        max_length=200, verbose_name="Фамилия Имя Отчество"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "parameter12",
                    models.CharField(
                        max_length=3,
                        verbose_name="Неприятное ощущение сильного или нерегулярного сердцебиения при нагрузке или в покое",
                    ),
                ),
                (
                    "parameter13",
                    models.CharField(
                        max_length=3,
                        verbose_name="Одышка при небольшой нагрузке или в покое",
                    ),
                ),
                (
                    "parameter14",
                    models.CharField(
                        max_length=3,
                        verbose_name="Потемнения в глазах, головокружения, обмороки, потеря равновесия",
                    ),
                ),
                (
                    "parameter11",
                    models.CharField(
                        max_length=3,
                        verbose_name="Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке",
                    ),
                ),
                (
                    "parameter15",
                    models.CharField(
                        max_length=3, verbose_name="Отечность лодыжек"
                    ),
                ),
                (
                    "parameter16",
                    models.CharField(
                        max_length=3,
                        verbose_name="Чувство жжения, боль, судороги в нижних конечностях при ходьбе на малые дистанции",
                    ),
                ),
                (
                    "parameter17",
                    models.CharField(
                        max_length=3,
                        verbose_name="Другие известные клиенту причины, по которым ему следует ограничить физическую активность",
                    ),
                ),
                (
                    "parameter20",
                    models.CharField(
                        max_length=3,
                        verbose_name="В течение как минимум последних трех месяцев проводятся регулярные тренировки длительностью не менее 30 минут в день, интенсивностью не ниже умеренной, с частотой не менее трех раз в неделю",
                    ),
                ),
                (
                    "parameter31",
                    models.CharField(
                        max_length=3, verbose_name="Инфаркт миокарда"
                    ),
                ),
                (
                    "parameter32",
                    models.CharField(
                        max_length=3,
                        verbose_name="Катетеризация сердца, коронарная ангиопластика, операции на сердце, трансплантация сердца",
                    ),
                ),
                (
                    "parameter33",
                    models.CharField(
                        max_length=3,
                        verbose_name="Нарушения сердечного ритма, кардиостимулятор/имплантируемый сердечный дефибриллятор",
                    ),
                ),
                (
                    "parameter34",
                    models.CharField(
                        max_length=3,
                        verbose_name="Врожденные пороки сердца, патологии сердечных клапанов, сердечная недостаточность",
                    ),
                ),
                (
                    "parameter35",
                    models.CharField(
                        max_length=3, verbose_name="Сахарный диабет"
                    ),
                ),
                (
                    "parameter36",
                    models.CharField(
                        max_length=3, verbose_name="Заболевания почек"
                    ),
                ),
                (
                    "norm_pressure",
                    models.CharField(
                        max_length=100,
                        verbose_name="Знаете ли Вы свое обычное артериальное давление?",
                    ),
                ),
                (
                    "parameter42",
                    models.CharField(
                        max_length=100,
                        verbose_name="Имеются ли у Вас изменения нормального уровня глюкозы в крови?",
                    ),
                ),
                (
                    "parameter43",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли у Вас заболевания мочевыделительной системы?",
                    ),
                ),
                (
                    "parameter44",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли у Вас заболевания дыхательной системы?",
                    ),
                ),
                (
                    "parameter45",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли у Вас заболевания пищеварительной системы?",
                    ),
                ),
                (
                    "parameter46",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли у Вас онкологические заболевания?",
                    ),
                ),
                (
                    "parameter47",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли у Вас заболевания периферических сосудов?",
                    ),
                ),
                (
                    "parameter48",
                    models.TextField(
                        verbose_name="Были ли у Вас травмы и хирургические операции?"
                    ),
                ),
                (
                    "parameter49",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли у Вас остеопороз, проблемы со спиной и суставами?",
                    ),
                ),
                (
                    "parameter410",
                    models.TextField(
                        verbose_name="Принимаете ли Вы в настоящее время лекарства?"
                    ),
                ),
                (
                    "parameter411",
                    models.CharField(
                        max_length=100, verbose_name="Беременны ли Вы?"
                    ),
                ),
                (
                    "parameter412",
                    models.CharField(
                        max_length=255,
                        verbose_name="Были ли у Вас роды в последние 6 месяцев?",
                    ),
                ),
                (
                    "parameter413",
                    models.TextField(
                        verbose_name="Есть ли у Вас заболевания, не упомянутые в этой анкете?"
                    ),
                ),
                (
                    "parameter414",
                    models.TextField(verbose_name="Соблюдаете ли Вы диету?"),
                ),
                (
                    "parameter415",
                    models.TextField(
                        verbose_name="Были ли у Вас в прошлом занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)?"
                    ),
                ),
                (
                    "parameter416",
                    models.CharField(
                        max_length=6,
                        verbose_name="Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)?",
                    ),
                ),
                (
                    "parameter416_exp",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Cтаж занятий",
                    ),
                ),
                (
                    "parameter417",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли признаки, которые позволяют заподозрить недовосстановление или перетренированность? (длительная усталость/ощущение утренней разбитости после тренировок, снижение работоспособности, раздражительность или перепады настроения, сильное нежелание тренироваться, нарушения сна)",
                    ),
                ),
                (
                    "parameter418",
                    models.CharField(
                        max_length=255,
                        verbose_name="Имеются ли особенности режима работы и отдыха, которые могут повлиять на переносимость нагрузок и восстановление после них? (сменный или ненормированный рабочий день, частые авралы на работе, невозможность полноценного сна, проблемы с регулярным питанием и пр.)",
                    ),
                ),
                (
                    "parameter419",
                    models.TextField(
                        verbose_name="Имеются ли не отраженные в анкете моменты, которые могут вызвать трудности при проведении тренировок/тестов на физическую подготовленность?"
                    ),
                ),
                (
                    "confirm",
                    models.BooleanField(
                        default=False,
                        verbose_name="Подверждаю достоверность предоставленных сведений и даю согласие на обработку персональных данных",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета здоровья клиента",
                "verbose_name_plural": "Анкеты здоровья клиентов",
            },
        ),
        migrations.CreateModel(
            name="ClientMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "general",
                    models.TextField(
                        blank=True, default="", verbose_name="Общее"
                    ),
                ),
                (
                    "measurements",
                    models.TextField(
                        blank=True, default="", verbose_name="Измерения"
                    ),
                ),
                (
                    "nutrition",
                    models.TextField(
                        blank=True, default="", verbose_name="Питание"
                    ),
                ),
                (
                    "workout",
                    models.TextField(
                        blank=True, default="", verbose_name="Тренировки"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Личная заметка клиента",
                "verbose_name_plural": "Личные заметки клиентов",
            },
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Telegram",
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Whatsapp",
                    ),
                ),
                (
                    "discord",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Discord",
                    ),
                ),
                (
                    "skype",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Skype",
                    ),
                ),
                (
                    "vkontakte",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Vkontakte",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("TG", "Telegram"),
                            ("WA", "Whatsapp"),
                            ("DC", "Discord"),
                            ("SK", "Skype"),
                            ("VK", "Vkontakte"),
                            ("FB", "Facebook"),
                            ("No", "не выбрано"),
                        ],
                        default="No",
                        max_length=2,
                        verbose_name="Предпочтительный способ связи",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты клиента",
                "verbose_name_plural": "Контакты клиентов",
            },
        ),
    ]
