# Generated by Django 4.2.5 on 2023-12-23 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "general",
                    models.TextField(blank=True, null=True, verbose_name="Общее"),
                ),
                (
                    "measurements",
                    models.TextField(blank=True, null=True, verbose_name="Измерения"),
                ),
                (
                    "nutrition",
                    models.TextField(blank=True, null=True, verbose_name="Питание"),
                ),
                (
                    "workout",
                    models.TextField(blank=True, null=True, verbose_name="Тренировки"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_time",
                    models.DateField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "modelname",
                    models.CharField(max_length=255, verbose_name="Модель данных"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "История действий",
                "verbose_name_plural": "Истории действий",
            },
        ),
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmation",
                    models.BooleanField(
                        default=False,
                        verbose_name="Подверждаю достоверность предоставляемых сведений и даю согласие на обработку персональных данных.",
                    ),
                ),
                (
                    "palpitation",
                    models.BooleanField(
                        default=False,
                        verbose_name="Неприятное ощущение сильного или нерегулярного сердцебиения при нагрузке или в покое.",
                    ),
                ),
                (
                    "dyspnea",
                    models.BooleanField(
                        default=False,
                        verbose_name="Одышка при небольшой нагрузке или в покое.",
                    ),
                ),
                (
                    "fainting",
                    models.BooleanField(
                        default=False,
                        verbose_name="Потемнения в глазах, головокружения, обмороки, потеря равновесия.",
                    ),
                ),
                (
                    "chest_pain",
                    models.BooleanField(
                        default=False,
                        verbose_name="Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке.",
                    ),
                ),
                (
                    "ankles_swelling",
                    models.BooleanField(
                        default=False, verbose_name="Отечность лодыжек."
                    ),
                ),
                (
                    "leg_cramps",
                    models.BooleanField(
                        default=False,
                        verbose_name="Чувство жжения, боль, судороги в нижних конечностях при ходьбе на малые дистанции.",
                    ),
                ),
                (
                    "restriction_reasons",
                    models.BooleanField(
                        default=False,
                        verbose_name="Другие известные причины, по которым следует ограничить физическую активность.",
                    ),
                ),
                (
                    "heart_attack",
                    models.BooleanField(default=False, verbose_name="Инфаркт миокарда."),
                ),
                (
                    "cardiac_surgery",
                    models.BooleanField(
                        default=False,
                        verbose_name="Катетеризация сердца, коронарная ангиопластика, операции на сердце, трансплантация сердца.",
                    ),
                ),
                (
                    "pacemaker",
                    models.BooleanField(
                        default=False,
                        verbose_name="Кардиостимулятор/имплантируемый сердечный дефибриллятор.",
                    ),
                ),
                (
                    "arrhythmia",
                    models.BooleanField(
                        default=False, verbose_name="Нарушения сердечного ритма."
                    ),
                ),
                (
                    "heart_defect",
                    models.BooleanField(
                        default=False,
                        verbose_name="Врожденные пороки сердца, патологии сердечных клапанов, сердечная недостаточность.",
                    ),
                ),
                (
                    "diabetes",
                    models.BooleanField(default=False, verbose_name="Сахарный диабет."),
                ),
                (
                    "kidney_disease",
                    models.BooleanField(
                        default=False, verbose_name="Заболевания почек."
                    ),
                ),
                (
                    "known_blood_pressure",
                    models.BooleanField(
                        default=False,
                        verbose_name="Знаете ли Вы свое обычное артериальное давление?",
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ваше обычное артериальное давление",
                    ),
                ),
                (
                    "has_glucose_changes",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли у Вас изменения нормального уровня глюкозы в крови?",
                    ),
                ),
                (
                    "glucose_level",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Укажите свой уровень сахара в крови",
                    ),
                ),
                (
                    "has_urinary_diseases",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли у Вас заболевания мочевыделительной системы?",
                    ),
                ),
                (
                    "urinary_diseases",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Перечислите имеющиеся заболевания мочевыделительной системы",
                    ),
                ),
                (
                    "has_respiratory_diseases",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли у Вас заболевания дыхательной системы?",
                    ),
                ),
                (
                    "respiratory_diseases",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Перечислите имеющиеся заболевания дыхательной системы",
                    ),
                ),
                (
                    "has_digestive_diseases",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли у Вас заболевания пищеварительной системы?",
                    ),
                ),
                (
                    "digestive_diseases",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Перечислите имеющиеся заболевания пищеварительной системы",
                    ),
                ),
                (
                    "has_oncological_diseases",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли у Вас онкологические заболевания?",
                    ),
                ),
                (
                    "oncological_diseases",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Перечислите имеющиеся онкологические заболевания",
                    ),
                ),
                (
                    "has_vascular_diseases",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли у Вас заболевания периферических сосудов?",
                    ),
                ),
                (
                    "vascular_diseases",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Перечислите имеющиеся заболевания периферических сосудов",
                    ),
                ),
                (
                    "has_trauma_or_surgeries",
                    models.BooleanField(
                        default=False,
                        verbose_name="Были ли у Вас травмы и хирургические операции?",
                    ),
                ),
                (
                    "trauma_or_surgeries",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Перечислите травмы и хирургические операции и время их происшествия",
                    ),
                ),
                (
                    "has_osteoporosis_and_joint_problems",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли у Вас остеопороз, проблемы со спиной и суставами?",
                    ),
                ),
                (
                    "osteoporosis_and_joint_problems",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Перечислите имеющиеся проблемы со спиной и суставами",
                    ),
                ),
                (
                    "has_other_diseases",
                    models.BooleanField(
                        default=False,
                        verbose_name="Есть ли у Вас заболевания, не упомянутые в этой анкете?",
                    ),
                ),
                (
                    "other_diseases",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Перечислите имеющиеся заболевания, не упомянутые в этой анкете",
                    ),
                ),
                (
                    "use_medications",
                    models.BooleanField(
                        default=False,
                        verbose_name="Принимаете ли Вы в настоящее время лекарства?",
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Перечислите принимаемые лекарства",
                    ),
                ),
                (
                    "follow_diet",
                    models.BooleanField(
                        default=False, verbose_name="Соблюдаете ли Вы диету?"
                    ),
                ),
                (
                    "current_diet",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Укажите вашу текущую диету",
                    ),
                ),
                (
                    "is_pregnant",
                    models.BooleanField(default=False, verbose_name="Беременны ли Вы?"),
                ),
                (
                    "pregnancy_stage",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Срок беременности",
                    ),
                ),
                (
                    "had_birth_in_last_six_months",
                    models.BooleanField(
                        default=False,
                        verbose_name="Были ли у Вас роды в последние 6 месяцев?",
                    ),
                ),
                (
                    "birth_complications",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Укажите, были ли осложнения до, во время и после родов и какие",
                    ),
                ),
                (
                    "has_regular_training",
                    models.BooleanField(
                        default=False,
                        verbose_name="В течение как минимум последних трех месяцев проводятся регулярные тренировки длительностью не менее 30 минут в день, интенсивностью не ниже умеренной, с частотой не менее трех раз в неделю.",
                    ),
                ),
                (
                    "had_physical_activity",
                    models.BooleanField(
                        default=False,
                        help_text="Cпорт, фитнес, танцы, йога и пр.",
                        verbose_name="Были ли у Вас в прошлом занятия, связанные с двигательной активностью?",
                    ),
                ),
                (
                    "previous_physical_activity",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Перечислите какие Вы имели занятия, связанные с двигательной активностью, и когда",
                    ),
                ),
                (
                    "current_physical_activity",
                    models.CharField(
                        choices=[
                            (
                                "H",
                                "3 занятия в неделю или больше, занятия регулярные, нагрузки от значительных до предельных",
                            ),
                            (
                                "M",
                                "2–3 занятия в неделю, занятия достаточно регулярные, нагрузки от умеренных до значительных",
                            ),
                            (
                                "L",
                                "меньше 2 занятий в неделю, занятия нерегулярные, нагрузки от незначительных до умеренных",
                            ),
                            ("N", "нет занятий"),
                        ],
                        max_length=1,
                        verbose_name="Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью ?",
                    ),
                ),
                (
                    "current_physical_activity_period",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Cтаж занятий текущей активностью",
                    ),
                ),
                (
                    "has_signs_of_underrecovery_or_overtraining",
                    models.BooleanField(
                        default=False,
                        help_text="Например, длительная усталость/ощущение утренней разбитости после тренировок, снижение работоспособности, раздражительность или перепады настроения, сильное нежелание тренироваться, нарушения сна.",
                        verbose_name="Имеются ли признаки, которые позволяют заподозрить недовосстановление или перетренированность?",
                    ),
                ),
                (
                    "signs_of_underrecovery_or_overtraining",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Перечислите признаки недовосстановления или перетренированности",
                    ),
                ),
                (
                    "has_work_rest_schedule_issues",
                    models.BooleanField(
                        default=False,
                        help_text="Например, сменный или ненормированный рабочий день, частые авралы на работе, невозможность полноценного сна, проблемы с регулярным питанием и пр.",
                        verbose_name="Имеются ли особенности режима работы и отдыха, которые могут повлиять на переносимость нагрузок и восстановление после них?",
                    ),
                ),
                (
                    "work_rest_schedule_issues",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Перечислите имеющиеся особенности режима работы и отдыха, которые могут повлиять на переносимость нагрузок и восстановление",
                    ),
                ),
                (
                    "has_other_issues",
                    models.BooleanField(
                        default=False,
                        verbose_name="Имеются ли не отраженные в анкете моменты, которые могут вызвать трудности при проведении тренировок/тестов на физическую подготовленность?",
                    ),
                ),
                (
                    "other_issues",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Перечислите остальные моменты, которые могут вызвать трудности при проведении тренировок/тестов на физическую подготовленность",
                    ),
                ),
                (
                    "is_filled",
                    models.BooleanField(default=False, verbose_name="Анкета заполнена"),
                ),
                (
                    "workout_readiness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("H", "Высокий уровень"),
                            ("M", "Средний уровень"),
                            ("L", "Низкий уровень"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Готовность к нагрузкам",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о здоровье",
                "verbose_name_plural": "Информация о здоровье",
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        help_text="Пример: https://t.me/demmenty",
                        max_length=250,
                        null=True,
                        verbose_name="Telegram",
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True,
                        help_text="Пример: https://wa.me/79603280691",
                        max_length=250,
                        null=True,
                        verbose_name="Whatsapp",
                    ),
                ),
                (
                    "discord",
                    models.CharField(
                        blank=True,
                        help_text="Пример: Demmenty#5187",
                        max_length=250,
                        null=True,
                        verbose_name="Discord",
                    ),
                ),
                (
                    "skype",
                    models.URLField(
                        blank=True,
                        help_text="Пример: join.skype.com/invite/ANfPTptWeOxA",
                        max_length=250,
                        null=True,
                        verbose_name="Skype",
                    ),
                ),
                (
                    "vkontakte",
                    models.URLField(
                        blank=True,
                        help_text="Пример: https://vk.com/id93683216",
                        max_length=250,
                        null=True,
                        verbose_name="Vkontakte",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        help_text="Пример: https://www.facebook.com/parabola.parabola.963",
                        max_length=250,
                        null=True,
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EM", "Email"),
                            ("TG", "Telegram"),
                            ("WA", "Whatsapp"),
                            ("DC", "Discord"),
                            ("SK", "Skype"),
                            ("VK", "Vkontakte"),
                            ("FB", "Facebook"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Предпочтительный способ связи",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты клиента",
                "verbose_name_plural": "Контакты клиентов",
            },
        ),
    ]
