# Generated by Django 4.2.5 on 2023-12-25 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
    ]
