# Generated by Django 4.2.5 on 2023-12-26 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0002_alter_contacts_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_current",
                    models.PositiveSmallIntegerField(verbose_name="Текущий вес"),
                ),
                (
                    "weight_min",
                    models.PositiveSmallIntegerField(
                        verbose_name="Минимальный вес за последние 5 лет"
                    ),
                ),
                (
                    "weight_max",
                    models.PositiveSmallIntegerField(
                        verbose_name="Максимальный вес за последние 5 лет"
                    ),
                ),
                (
                    "weight_avg",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="указывать, если сейчас 30 лет и более",
                        null=True,
                        verbose_name="Средний вес между 20-25 годами",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вес",
                "verbose_name_plural": "Вес",
            },
        ),
    ]
