# Generated by Django 4.2.5 on 2023-10-06 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChangeLog",
            new_name="Log",
        ),
        migrations.AlterField(
            model_name="health",
            name="ankles_swelling",
            field=models.BooleanField(
                default=False, verbose_name="Отечность лодыжек"
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="arrhythmia",
            field=models.BooleanField(
                default=False, verbose_name="Нарушения сердечного ритма"
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="cardiac_surgery",
            field=models.BooleanField(
                default=False,
                verbose_name="Катетеризация сердца, коронарная ангиопластика, операции на сердце, трансплантация сердца",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="chest_pain",
            field=models.BooleanField(
                default=False,
                verbose_name="Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="confirmation",
            field=models.BooleanField(
                default=False,
                verbose_name="Подверждаю достоверность предоставляемых сведений и даю согласие на обработку персональных данных",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="current_physical_activity",
            field=models.CharField(
                choices=[
                    (
                        "H",
                        "3 занятия в неделю или больше, занятия регулярные, нагрузки от значительных до предельных",
                    ),
                    (
                        "M",
                        "2–3 занятия в неделю, занятия достаточно регулярные, нагрузки от умеренных до значительных",
                    ),
                    (
                        "L",
                        "меньше 2 занятий в неделю, занятия нерегулярные, нагрузки от незначительных до умеренных",
                    ),
                    ("N", "нет занятий"),
                ],
                help_text="Cпорт, фитнес, танцы, йога и пр.",
                max_length=1,
                verbose_name="Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью ?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="diabetes",
            field=models.BooleanField(
                default=False, verbose_name="Сахарный диабет"
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="dyspnea",
            field=models.BooleanField(
                default=False,
                verbose_name="Одышка при небольшой нагрузке или в покое",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="fainting",
            field=models.BooleanField(
                default=False,
                verbose_name="Потемнения в глазах, головокружения, обмороки, потеря равновесия",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="follow_diet",
            field=models.BooleanField(
                default=False, verbose_name="Соблюдаете ли Вы диету?"
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="had_birth_in_last_six_months",
            field=models.BooleanField(
                default=False,
                verbose_name="Были ли у Вас роды в последние 6 месяцев?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="had_physical_activity",
            field=models.BooleanField(
                default=False,
                help_text="Cпорт, фитнес, танцы, йога и пр.",
                verbose_name="Были ли у Вас в прошлом занятия, связанные с двигательной активностью?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_digestive_diseases",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли у Вас заболевания пищеварительной системы?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_glucose_changes",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли у Вас изменения нормального уровня глюкозы в крови?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_oncological_diseases",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли у Вас онкологические заболевания?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_osteoporosis_and_joint_problems",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли у Вас остеопороз, проблемы со спиной и суставами?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_other_diseases",
            field=models.BooleanField(
                default=False,
                verbose_name="Есть ли у Вас заболевания, не упомянутые в этой анкете?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_other_issues",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли не отраженные в анкете моменты, которые могут вызвать трудности при проведении тренировок/тестов на физическую подготовленность?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_regular_training",
            field=models.BooleanField(
                default=False,
                verbose_name="В течение как минимум последних трех месяцев проводятся регулярные тренировки длительностью не менее 30 минут в день, интенсивностью не ниже умеренной, с частотой не менее трех раз в неделю",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_respiratory_diseases",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли у Вас заболевания дыхательной системы?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_signs_of_underrecovery_or_overtraining",
            field=models.BooleanField(
                default=False,
                help_text="Например, длительная усталость/ощущение утренней разбитости после тренировок, снижение работоспособности, раздражительность или перепады настроения, сильное нежелание тренироваться, нарушения сна.",
                verbose_name="Имеются ли признаки, которые позволяют заподозрить недовосстановление или перетренированность?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_trauma_or_surgeries",
            field=models.BooleanField(
                default=False,
                verbose_name="Были ли у Вас травмы и хирургические операции?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_urinary_diseases",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли у Вас заболевания мочевыделительной системы?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_vascular_diseases",
            field=models.BooleanField(
                default=False,
                verbose_name="Имеются ли у Вас заболевания периферических сосудов?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_work_rest_schedule_issues",
            field=models.BooleanField(
                default=False,
                help_text="Например, сменный или ненормированный рабочий день, частые авралы на работе, невозможность полноценного сна, проблемы с регулярным питанием и пр.",
                verbose_name="Имеются ли особенности режима работы и отдыха, которые могут повлиять на переносимость нагрузок и восстановление после них?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="heart_attack",
            field=models.BooleanField(
                default=False, verbose_name="Инфаркт миокарда"
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="heart_defect",
            field=models.BooleanField(
                default=False,
                verbose_name="Врожденные пороки сердца, патологии сердечных клапанов, сердечная недостаточность",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="is_pregnant",
            field=models.BooleanField(
                default=False, verbose_name="Беременны ли Вы?"
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="kidney_disease",
            field=models.BooleanField(
                default=False, verbose_name="Заболевания почек"
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="known_blood_pressure",
            field=models.BooleanField(
                default=False,
                verbose_name="Знаете ли Вы свое обычное артериальное давление?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="leg_cramps",
            field=models.BooleanField(
                default=False,
                verbose_name="Чувство жжения, боль, судороги в нижних конечностях при ходьбе на малые дистанции",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="pacemaker",
            field=models.BooleanField(
                default=False,
                verbose_name="Кардиостимулятор/имплантируемый сердечный дефибриллятор",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="palpitation",
            field=models.BooleanField(
                default=False,
                verbose_name="Неприятное ощущение сильного или нерегулярного сердцебиения при нагрузке или в покое",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="restriction_reasons",
            field=models.BooleanField(
                default=False,
                verbose_name="Другие известные причины, по которым следует ограничить физическую активность",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="use_medications",
            field=models.BooleanField(
                default=False,
                verbose_name="Принимаете ли Вы в настоящее время лекарства?",
            ),
        ),
    ]
