# Generated by Django 4.2.5 on 2023-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "client",
            "0003_rename_changelog_log_alter_health_ankles_swelling_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="health",
            options={
                "verbose_name": "Информация о здоровье",
                "verbose_name_plural": "Информация о здоровье",
            },
        ),
        migrations.AlterModelOptions(
            name="log",
            options={
                "verbose_name": "История действий",
                "verbose_name_plural": "Истории действий",
            },
        ),
        migrations.AddField(
            model_name="log",
            name="modelname",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="health",
            name="current_physical_activity",
            field=models.CharField(
                choices=[
                    (
                        "H",
                        "3 занятия в неделю или больше, занятия регулярные, нагрузки от значительных до предельных",
                    ),
                    (
                        "M",
                        "2–3 занятия в неделю, занятия достаточно регулярные, нагрузки от умеренных до значительных",
                    ),
                    (
                        "L",
                        "меньше 2 занятий в неделю, занятия нерегулярные, нагрузки от незначительных до умеренных",
                    ),
                    ("N", "нет занятий"),
                ],
                max_length=1,
                verbose_name="Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью ?",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="current_physical_activity_period",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Cтаж занятий текущей активностью",
            ),
        ),
    ]
