# Generated by Django 4.2.5 on 2023-12-26 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0003_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sleep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_asleep",
                    models.CharField(max_length=255, verbose_name="Время укладывания"),
                ),
                (
                    "time_wakeup",
                    models.CharField(max_length=255, verbose_name="Время вставания"),
                ),
                (
                    "problems",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Как часто нарушается сон и на какое время",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сон",
                "verbose_name_plural": "Сон",
            },
        ),
    ]
