# Generated by Django 4.2.5 on 2023-10-07 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "client",
            "0004_alter_health_options_alter_log_options_log_modelname_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="health",
            name="workout_readiness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("H", "Высокий уровень"),
                    ("M", "Средний уровень"),
                    ("L", "Низкий уровень"),
                ],
                max_length=1,
                null=True,
                verbose_name="Готовность к нагрузкам",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="ankles_swelling",
            field=models.BooleanField(
                default=False, verbose_name="Отечность лодыжек."
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="arrhythmia",
            field=models.BooleanField(
                default=False, verbose_name="Нарушения сердечного ритма."
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="cardiac_surgery",
            field=models.BooleanField(
                default=False,
                verbose_name="Катетеризация сердца, коронарная ангиопластика, операции на сердце, трансплантация сердца.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="chest_pain",
            field=models.BooleanField(
                default=False,
                verbose_name="Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="confirmation",
            field=models.BooleanField(
                default=False,
                verbose_name="Подверждаю достоверность предоставляемых сведений и даю согласие на обработку персональных данных.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="diabetes",
            field=models.BooleanField(
                default=False, verbose_name="Сахарный диабет."
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="dyspnea",
            field=models.BooleanField(
                default=False,
                verbose_name="Одышка при небольшой нагрузке или в покое.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="fainting",
            field=models.BooleanField(
                default=False,
                verbose_name="Потемнения в глазах, головокружения, обмороки, потеря равновесия.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="has_regular_training",
            field=models.BooleanField(
                default=False,
                verbose_name="В течение как минимум последних трех месяцев проводятся регулярные тренировки длительностью не менее 30 минут в день, интенсивностью не ниже умеренной, с частотой не менее трех раз в неделю.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="heart_attack",
            field=models.BooleanField(
                default=False, verbose_name="Инфаркт миокарда."
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="heart_defect",
            field=models.BooleanField(
                default=False,
                verbose_name="Врожденные пороки сердца, патологии сердечных клапанов, сердечная недостаточность.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="kidney_disease",
            field=models.BooleanField(
                default=False, verbose_name="Заболевания почек."
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="leg_cramps",
            field=models.BooleanField(
                default=False,
                verbose_name="Чувство жжения, боль, судороги в нижних конечностях при ходьбе на малые дистанции.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="pacemaker",
            field=models.BooleanField(
                default=False,
                verbose_name="Кардиостимулятор/имплантируемый сердечный дефибриллятор.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="palpitation",
            field=models.BooleanField(
                default=False,
                verbose_name="Неприятное ощущение сильного или нерегулярного сердцебиения при нагрузке или в покое.",
            ),
        ),
        migrations.AlterField(
            model_name="health",
            name="restriction_reasons",
            field=models.BooleanField(
                default=False,
                verbose_name="Другие известные причины, по которым следует ограничить физическую активность.",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="change_message",
            field=models.CharField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="log",
            name="modelname",
            field=models.CharField(
                max_length=255, verbose_name="Модель данных"
            ),
        ),
        migrations.CreateModel(
            name="MainData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Мужской"),
                            ("F", "Женский"),
                            ("X", "Другое"),
                        ],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(verbose_name="Рост"),
                ),
                ("birthday", models.DateField(verbose_name="День рождения")),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Основная информация",
                "verbose_name_plural": "Основная информация",
            },
        ),
    ]
