# Generated by Django 4.2.5 on 2023-12-26 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0004_sleep"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_meal_amount",
                    models.CharField(
                        max_length=255,
                        verbose_name="Количество полноценных приёмов пищи в сутки",
                    ),
                ),
                (
                    "daily_snack_amount",
                    models.CharField(
                        max_length=255, verbose_name="Количество перекусов в сутки"
                    ),
                ),
                (
                    "common",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы едите наиболее часто и регулярно"
                    ),
                ),
                (
                    "weekly",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы едите примерно раз в неделю"
                    ),
                ),
                (
                    "yearly",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы едите несколько раз в год"
                    ),
                ),
                (
                    "favorite",
                    models.TextField(
                        verbose_name="5 видов пищи, которую вы считаете самой вкусной, желанной и любимой"
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Питание",
                "verbose_name_plural": "Питание",
            },
        ),
    ]
