# Generated by Django 4.2.5 on 2023-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_health_workout_readiness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maindata",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="client/avatars",
                verbose_name="Аватар",
            ),
        ),
    ]
