# Generated by Django 4.2.5 on 2023-12-26 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0005_food"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Ваша цель")),
                (
                    "measure",
                    models.TextField(
                        verbose_name="Какой показатель поможет нам эту цель измерить? (например, килограммы)"
                    ),
                ),
                (
                    "attempts",
                    models.TextField(
                        verbose_name="Были ли ранее попытки достичь этой цели? Опишите их и назовите количество"
                    ),
                ),
                (
                    "obstacles",
                    models.TextField(
                        verbose_name="Главные препятствия к достижению вашей цели"
                    ),
                ),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        verbose_name="Насколько важна указанная цель"
                    ),
                ),
                (
                    "maxtime",
                    models.TextField(
                        verbose_name="Какое максимальное количество времени можно уделить достижению цели"
                    ),
                ),
                (
                    "readiness",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "Не вижу необходимости в серьёзных переменах, хочу лишь слегка скорректировать образ жизни.",
                            ),
                            (
                                "2",
                                "Готов к переменам в образе жизни, скоро начну их воплощать.",
                            ),
                            (
                                "3",
                                "Хочу изменить свой образ жизни, но не уверен, что смогу.",
                            ),
                            (
                                "4",
                                "Начал менять образ жизни в течение последнего полугода.",
                            ),
                            (
                                "5",
                                "Работаю над изменением образа жизни, но чувствую, что нуждаюсь в помощи, чтобы продвинуться дальше.",
                            ),
                            (
                                "6",
                                "Активно работаю над собой, продвигаюсь, но хочу делать это ещё лучше.",
                            ),
                        ],
                        max_length=1,
                        verbose_name="Готовность к изменениям",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цель",
            },
        ),
    ]
