# Generated by Django 4.2.5 on 2023-10-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0006_maindata_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maindata",
            name="avatar",
        ),
        migrations.AlterField(
            model_name="maindata",
            name="height",
            field=models.PositiveSmallIntegerField(
                help_text="Нужен для расчетов, например, индекса массы тела.",
                verbose_name="Рост (см)",
            ),
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Telegram",
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Whatsapp",
                    ),
                ),
                (
                    "discord",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Discord",
                    ),
                ),
                (
                    "skype",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Skype",
                    ),
                ),
                (
                    "vkontakte",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Vkontakte",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EM", "Email"),
                            ("TG", "Telegram"),
                            ("WA", "Whatsapp"),
                            ("DC", "Discord"),
                            ("SK", "Skype"),
                            ("VK", "Vkontakte"),
                            ("FB", "Facebook"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Предпочтительный способ связи",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты клиента",
                "verbose_name_plural": "Контакты клиентов",
            },
        ),
    ]
