# Generated by Django 4.2.5 on 2023-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "client",
            "0007_remove_maindata_avatar_alter_maindata_height_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="discord",
            field=models.CharField(
                blank=True,
                help_text="Пример: Demmenty#5187",
                max_length=250,
                null=True,
                verbose_name="Discord",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="facebook",
            field=models.URLField(
                blank=True,
                help_text="Пример: https://www.facebook.com/parabola.parabola.963",
                max_length=250,
                null=True,
                verbose_name="Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="skype",
            field=models.URLField(
                blank=True,
                help_text="Пример: join.skype.com/invite/ANfPTptWeOxA",
                max_length=250,
                null=True,
                verbose_name="Skype",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="telegram",
            field=models.URLField(
                blank=True,
                help_text="Пример: https://t.me/demmenty",
                max_length=250,
                null=True,
                verbose_name="Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="vkontakte",
            field=models.URLField(
                blank=True,
                help_text="Пример: https://vk.com/id93683216",
                max_length=250,
                null=True,
                verbose_name="Vkontakte",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="whatsapp",
            field=models.URLField(
                blank=True,
                help_text="Пример: https://wa.me/79603280691",
                max_length=250,
                null=True,
                verbose_name="Whatsapp",
            ),
        ),
    ]
