# Generated by Django 4.2.5 on 2023-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_alter_food_options_alter_goal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="health",
            name="daily_steps",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Среднее количество шагов в сутки",
            ),
            preserve_default=False,
        ),
    ]
