# Generated by Django 4.2.5 on 2023-12-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_health_daily_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="link",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
