# Generated by Django 4.2.5 on 2023-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_alter_contacts_discord_alter_contacts_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maindata",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="client/avatars", verbose_name="Аватар"
            ),
        ),
    ]
