# Generated by Django 4.2.5 on 2023-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0009_maindata_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="health",
            name="is_filled",
            field=models.BooleanField(default=False, verbose_name="Анкета заполнена"),
        ),
    ]
