# Generated by Django 4.2.5 on 2024-02-18 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="rate",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(default="", verbose_name="Отзыв"),
            preserve_default=False,
        ),
    ]
