# Generated by Django 4.2.5 on 2023-11-30 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0011_rename_change_message_log_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainData",
        ),
    ]
