# Generated by Django 4.2.5 on 2023-12-21 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0012_delete_maindata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "general",
                    models.TextField(blank=True, null=True, verbose_name="Общее"),
                ),
                (
                    "measurements",
                    models.TextField(blank=True, null=True, verbose_name="Измерения"),
                ),
                (
                    "nutrition",
                    models.TextField(blank=True, null=True, verbose_name="Питание"),
                ),
                (
                    "workout",
                    models.TextField(blank=True, null=True, verbose_name="Тренировки"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
            },
        ),
    ]
