[tool.black]
line-length = 79
target-version = ['py311']
exclude = '''
/(
  | \.git
  | \.mypy_cache
  | \.venv
  | media
  | static
  | migrations
  | env
  | venv
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
combine_as_imports = true
line_length = 80
skip_glob = ["*/*/alembic"]