# Generated by Django 4.2.5 on 2023-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="message",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="chat/audio",
                verbose_name="Аудио",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="chat/image",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="seen",
            field=models.BooleanField(default=False, verbose_name="Прочитано"),
        ),
    ]
