# Generated by Django 4.2.5 on 2023-11-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_remove_message_content_message_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image_height",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="image_width",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
