# Generated by Django 4.2.5 on 2023-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_image_height_message_image_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image_height",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Высота изображения (пиксели)"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="image_width",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ширина изображения (пиксели)"
            ),
        ),
    ]
