# Generated by Django 4.1 on 2022-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='general_read',
            field=models.BooleanField(default=False, verbose_name='Общее - прочитано'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='measurements_read',
            field=models.BooleanField(default=False, verbose_name='Измерения - прочитано'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='nutrition_read',
            field=models.BooleanField(default=False, verbose_name='Питание - прочитано'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='workout_read',
            field=models.BooleanField(default=False, verbose_name='Тренировки - прочитано'),
        ),
    ]
