# Generated by Django 4.1 on 2022-12-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpage', '0003_consultationsignup_alter_commentary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationsignup',
            name='expert_comment',
        ),
        migrations.AddField(
            model_name='consultationsignup',
            name='expert_note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
    ]
