# Generated by Django 4.1 on 2023-01-05 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlpage', '0005_alter_consultationsignup_expert_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsignup',
            name='email',
            field=models.EmailField(blank=True, help_text='Обещаем не использовать адрес в коварных целях!', max_length=100, verbose_name='Почта'),
        ),
        migrations.CreateModel(
            name='Clientnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('general', models.TextField(blank=True, default='', verbose_name='Общее')),
                ('measurements', models.TextField(blank=True, default='', verbose_name='Измерения')),
                ('nutrition', models.TextField(blank=True, default='', verbose_name='Питание')),
                ('workout', models.TextField(blank=True, default='', verbose_name='Тренировки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
