# Generated by Django 4.1 on 2023-01-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlpage', '0006_alter_consultationsignup_email_clientnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultationsignup',
        ),
    ]
