# Generated by Django 4.2.5 on 2023-10-10 09:58

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#ffffff00",
                        max_length=20,
                        verbose_name="Цвет фона",
                    ),
                ),
                (
                    "meaning",
                    models.CharField(
                        max_length=100, verbose_name="Значение фона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Окрашивание дневных измерений",
                "verbose_name_plural": "Окрашивания дневных измерений",
            },
        ),
        migrations.CreateModel(
            name="MeasureIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_name",
                    models.CharField(max_length=50, verbose_name="Показатель"),
                ),
            ],
            options={
                "verbose_name": "Показатель измерений",
                "verbose_name_plural": "Показатели измерений",
            },
        ),
        migrations.CreateModel(
            name="MeasureColorField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        max_digits=5,
                        null=True,
                        verbose_name="Нижняя граница включительно",
                    ),
                ),
                (
                    "upper_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        max_digits=5,
                        null=True,
                        verbose_name="Верхняя граница включительно",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.measurecolor",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.measureindex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Границы цветов измерений для клиента",
                "verbose_name_plural": "Границы цветов измерений для клиентов",
            },
        ),
        migrations.CreateModel(
            name="AnthropometryPhotoAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_access",
                    models.BooleanField(
                        default=False, verbose_name="Доступ эксперта к фото"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к фото",
                "verbose_name_plural": "Доступы к фото",
            },
        ),
        migrations.CreateModel(
            name="Anthropometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата"
                    ),
                ),
                (
                    "shoulder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Плечо",
                    ),
                ),
                (
                    "chest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Грудь",
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Талия",
                    ),
                ),
                (
                    "belly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Живот",
                    ),
                ),
                (
                    "buttocks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Ягодицы",
                    ),
                ),
                (
                    "hip",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Бедро",
                    ),
                ),
                (
                    "shin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Голень",
                    ),
                ),
                (
                    "photo_1",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="anthropometry/img/clients/%Y/%d.%m",
                        verbose_name="Фото спереди",
                    ),
                ),
                (
                    "photo_2",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="anthropometry/img/clients/%Y/%d.%m",
                        verbose_name="Фото сзади",
                    ),
                ),
                (
                    "photo_3",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="anthropometry/img/clients/%Y/%d.%m",
                        verbose_name="Фото сбоку",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Антропометрия",
                "verbose_name_plural": "Антропометрии",
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
    ]
