# Generated by Django 4.2.5 on 2023-10-10 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "metrics",
            "0002_measurecolor_measureindex_measurecolorfield_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailydata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ежедневные измерения",
                "verbose_name_plural": "Ежедневные измерения",
            },
        ),
        migrations.RenameField(
            model_name="dailydata",
            old_name="date",
            new_name="created_at",
        ),
    ]
