# Generated by Django 4.2.5 on 2023-10-12 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0003_alter_dailydata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailydata",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Ежедневные измерения",
                "verbose_name_plural": "Ежедневные измерения",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailydata",
            unique_together={("client", "created_at")},
        ),
    ]
