# Generated by Django 4.2.5 on 2023-10-12 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0004_alter_dailydata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailydata",
            options={
                "ordering": ("date",),
                "verbose_name": "Ежедневные измерения",
                "verbose_name_plural": "Ежедневные измерения",
            },
        ),
        migrations.RenameField(
            model_name="dailydata",
            old_name="created_at",
            new_name="date",
        ),
        migrations.AlterUniqueTogether(
            name="dailydata",
            unique_together={("client", "date")},
        ),
    ]
