# Generated by Django 4.2.5 on 2023-10-12 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0005_alter_dailydata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailydata",
            options={
                "ordering": ("-date",),
                "verbose_name": "Ежедневные измерения",
                "verbose_name_plural": "Ежедневные измерения",
            },
        ),
    ]
