# Generated by Django 4.2.5 on 2023-10-12 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0006_alter_dailydata_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailydata",
            options={
                "ordering": ("date",),
                "verbose_name": "Ежедневные измерения",
                "verbose_name_plural": "Ежедневные измерения",
            },
        ),
    ]
