# Generated by Django 4.2.5 on 2023-10-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0009_colorset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorset",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="colorset",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("feel", "Самочувствие"),
                    ("weight", "Вес"),
                    ("fat", "Процент жира"),
                    ("pulse", "Пульс"),
                    ("pressure_upper", "Давление верхнее"),
                    ("pressure_lower", "Давление нижнее"),
                    ("calories", "Калории"),
                    ("protein", "Белки"),
                    ("fats", "Жиры"),
                    ("carbohydrates", "Углеводы"),
                ],
                max_length=14,
                verbose_name="Параметр",
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="fat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Количество жировой массы в процентах от массы тела",
                max_digits=3,
                null=True,
                verbose_name="Процент жира",
            ),
        ),
    ]
