# Generated by Django 4.2.5 on 2023-10-16 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0011_colors_rename_colorset_levels"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatSecretEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oauth_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oauth_token_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные доступа к Fatsecret",
                "verbose_name_plural": "Данные доступа к Fatsecret",
            },
        ),
        migrations.CreateModel(
            name="NutritionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calories",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Калории"
                    ),
                ),
                (
                    "protein",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Белки"
                    ),
                ),
                (
                    "fats",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Жиры"
                    ),
                ),
                (
                    "carbohydrates",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Углеводы"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекомендации КБЖУ",
                "verbose_name_plural": "Рекомендации КБЖУ",
            },
        ),
        migrations.RemoveField(
            model_name="measurecolorfield",
            name="client",
        ),
        migrations.RemoveField(
            model_name="measurecolorfield",
            name="color",
        ),
        migrations.RemoveField(
            model_name="measurecolorfield",
            name="index",
        ),
        migrations.AlterModelOptions(
            name="levels",
            options={
                "verbose_name": "Настройки уровней измерений",
                "verbose_name_plural": "Настройки уровней измерений",
            },
        ),
        migrations.AlterField(
            model_name="colors",
            name="lvl1",
            field=models.CharField(
                default="#66e5a2",
                help_text="идеально",
                max_length=7,
                verbose_name="Уровень 1",
            ),
        ),
        migrations.AlterField(
            model_name="colors",
            name="lvl2",
            field=models.CharField(
                default="#b2ff99",
                help_text="хорошо",
                max_length=7,
                verbose_name="Уровень 2",
            ),
        ),
        migrations.AlterField(
            model_name="colors",
            name="lvl3",
            field=models.CharField(
                default="#fffa88",
                help_text="неплохо",
                max_length=7,
                verbose_name="Уровень 3",
            ),
        ),
        migrations.AlterField(
            model_name="colors",
            name="lvl4",
            field=models.CharField(
                default="#ffd278",
                help_text="плохо",
                max_length=7,
                verbose_name="Уровень 4",
            ),
        ),
        migrations.AlterField(
            model_name="colors",
            name="lvl5",
            field=models.CharField(
                default="#ff998b",
                help_text="критично",
                max_length=7,
                verbose_name="Уровень 5",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="levels",
            unique_together={("client", "parameter")},
        ),
        migrations.DeleteModel(
            name="MeasureColor",
        ),
        migrations.DeleteModel(
            name="MeasureColorField",
        ),
        migrations.DeleteModel(
            name="MeasureIndex",
        ),
    ]
