# Generated by Django 4.2.5 on 2023-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0012_fatsecretentry_nutritionrecommendation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailydata",
            old_name="carbohydrates",
            new_name="carbs",
        ),
        migrations.RenameField(
            model_name="nutritionrecommendation",
            old_name="carbohydrates",
            new_name="carbs",
        ),
        migrations.AlterField(
            model_name="levels",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("feel", "Самочувствие"),
                    ("weight", "Вес"),
                    ("fat", "Процент жира"),
                    ("pulse", "Пульс"),
                    ("pressure_upper", "Давление верхнее"),
                    ("pressure_lower", "Давление нижнее"),
                    ("calories", "Калории"),
                    ("protein", "Белки"),
                    ("fats", "Жиры"),
                    ("carbs", "Углеводы"),
                ],
                max_length=14,
                verbose_name="Параметр",
            ),
        ),
    ]
