# Generated by Django 4.2.5 on 2023-10-19 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0013_rename_carbohydrates_dailydata_carbs_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NutritionRecommendation",
            new_name="NutritionRecs",
        ),
    ]
