# Generated by Django 4.2.5 on 2023-11-03 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0014_rename_nutritionrecommendation_nutritionrecs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FatSecretEntry",
        ),
    ]
