# Generated by Django 4.2.5 on 2023-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0015_delete_fatsecretentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailydata",
            old_name="carbs",
            new_name="carbohydrate",
        ),
        migrations.RenameField(
            model_name="nutritionrecs",
            old_name="carbs",
            new_name="carbohydrate",
        ),
        migrations.RenameField(
            model_name="nutritionrecs",
            old_name="fats",
            new_name="fat",
        ),
        migrations.RemoveField(
            model_name="dailydata",
            name="fats",
        ),
        migrations.AddField(
            model_name="dailydata",
            name="fat_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Количество жировой массы в процентах от массы тела",
                max_digits=3,
                null=True,
                verbose_name="Процент жира",
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="fat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Количество потребленных за день жиров в граммах",
                max_digits=6,
                null=True,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="levels",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("feel", "Самочувствие"),
                    ("weight", "Вес"),
                    ("fat_percentage", "Процент жира"),
                    ("pulse", "Пульс"),
                    ("pressure_upper", "Давление верхнее"),
                    ("pressure_lower", "Давление нижнее"),
                    ("calories", "Калории"),
                    ("protein", "Белки"),
                    ("fat", "Жиры"),
                    ("carbohydrate", "Углеводы"),
                ],
                max_length=14,
                verbose_name="Параметр",
            ),
        ),
    ]
