# Generated by Django 4.2.5 on 2023-12-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0017_delete_nutritionrecs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anthropometryphotoaccess",
            old_name="photo_access",
            new_name="access",
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clients/anthropometry/%Y/%d.%m",
                verbose_name="Фото спереди",
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clients/anthropometry/%Y/%d.%m",
                verbose_name="Фото сзади",
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clients/anthropometry/%Y/%d.%m",
                verbose_name="Фото сбоку",
            ),
        ),
    ]
