# Generated by Django 4.2.5 on 2023-12-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0018_rename_photo_access_anthropometryphotoaccess_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anthropometry",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата"),
        ),
    ]
