# Generated by Django 4.2.5 on 2023-12-03 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0019_alter_anthropometry_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anthropometryphotoaccess",
            old_name="access",
            new_name="is_allowed",
        ),
    ]
