# Generated by Django 4.2.5 on 2023-12-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0020_rename_access_anthropometryphotoaccess_is_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clients/anthropo_metrics/%Y/%d.%m",
                verbose_name="Фото спереди",
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clients/anthropo_metrics/%Y/%d.%m",
                verbose_name="Фото сзади",
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clients/anthropo_metrics/%Y/%d.%m",
                verbose_name="Фото сбоку",
            ),
        ),
    ]
