# Generated by Django 4.2.5 on 2023-12-05 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0021_alter_anthropometry_photo_1_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Anthropometry",
            new_name="Anthropo",
        ),
        migrations.RenameModel(
            old_name="DailyData",
            new_name="Daily",
        ),
        migrations.RenameModel(
            old_name="AnthropometryPhotoAccess",
            new_name="PhotoAccess",
        ),
        migrations.AlterModelOptions(
            name="anthropo",
            options={
                "get_latest_by": "date",
                "ordering": ["-date"],
                "verbose_name": "Антропометрия",
                "verbose_name_plural": "Антропометрия",
            },
        ),
        migrations.AlterModelOptions(
            name="photoaccess",
            options={
                "verbose_name": "Доступ к фото",
                "verbose_name_plural": "Доступ к фото",
            },
        ),
    ]
