# Generated by Django 4.1 on 2023-01-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationSignup',
        ),
    ]
