# Generated by Django 4.2.5 on 2023-10-10 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calories",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Рекомендуемое количество калорий",
                    ),
                ),
                (
                    "protein",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Рекомендуемое количество белков",
                    ),
                ),
                (
                    "fats",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Рекомендуемое количество жиров",
                    ),
                ),
                (
                    "carbohydrates",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Рекомендуемое количество углеводов",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", verbose_name="Заметка"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекомендация КБЖУ",
                "verbose_name_plural": "Рекомендации КБЖУ",
            },
        ),
        migrations.CreateModel(
            name="FatSecretEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oauth_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oauth_token_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные для входа в Fatsecret",
                "verbose_name_plural": "Данные для входа в Fatsecret",
            },
        ),
    ]
