# Generated by Django 4.2.5 on 2023-10-13 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fatsecretentry",
            options={
                "verbose_name": "Данные доступа к Fatsecret",
                "verbose_name_plural": "Данные доступа к Fatsecret",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendation",
            options={
                "verbose_name": "Рекомендации КБЖУ",
                "verbose_name_plural": "Рекомендации КБЖУ",
            },
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="note",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="comment",
            field=models.TextField(
                blank=True, default="", verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="fatsecretentry",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="calories",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Калории"
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="carbohydrates",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Углеводы"
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="fats",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Жиры"
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="protein",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Белки"
            ),
        ),
    ]
