# Generated by Django 4.2.5 on 2024-02-18 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Recommendation",
            new_name="Estimation",
        ),
        migrations.AlterModelOptions(
            name="estimation",
            options={
                "verbose_name": "Расчет КБЖУ",
                "verbose_name_plural": "Расчеты КБЖУ",
            },
        ),
    ]
