# Generated by Django 4.2.5 on 2023-10-16 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0002_alter_fatsecretentry_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="client",
        ),
        migrations.DeleteModel(
            name="FatSecretEntry",
        ),
        migrations.DeleteModel(
            name="Recommendation",
        ),
    ]
