# Generated by Django 4.2.5 on 2023-11-03 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "nutrition",
            "0003_remove_recommendation_client_delete_fatsecretentry_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FatSecretEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oauth_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oauth_token_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные доступа к Fatsecret",
                "verbose_name_plural": "Данные доступа к Fatsecret",
            },
        ),
    ]
