# Generated by Django 4.1 on 2023-01-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Идеальное количество калорий')),
                ('protein', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Идеальное количество белков')),
                ('fats', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Идеальное количество жиров')),
                ('carbohydrates', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Идеальное количество углеводов')),
                ('note', models.TextField(blank=True, default='', verbose_name='Заметка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
