# Generated by Django 4.1 on 2023-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionrecommendation',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рекомендуемое количество калорий'),
        ),
        migrations.AlterField(
            model_name='nutritionrecommendation',
            name='carbohydrates',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рекомендуемое количество углеводов'),
        ),
        migrations.AlterField(
            model_name='nutritionrecommendation',
            name='fats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рекомендуемое количество жиров'),
        ),
        migrations.AlterField(
            model_name='nutritionrecommendation',
            name='protein',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рекомендуемое количество белков'),
        ),
    ]
