# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "expert_recommendations",
            "0002_alter_nutritionrecommendation_calories_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutritionrecommendation",
            options={
                "verbose_name": "Рекомендация КБЖУ",
                "verbose_name_plural": "Рекомендации КБЖУ",
            },
        ),
    ]
