# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurecolor",
            options={
                "verbose_name": "Окрашивание дневных измерений",
                "verbose_name_plural": "Окрашивания дневных измерений",
            },
        ),
        migrations.AlterModelOptions(
            name="measurecolorfield",
            options={
                "verbose_name": "Границы цветов измерений для клиента",
                "verbose_name_plural": "Границы цветов измерений для клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="measureindex",
            options={
                "verbose_name": "Показатель измерений",
                "verbose_name_plural": "Показатели измерений",
            },
        ),
        migrations.AlterModelOptions(
            name="measurement",
            options={
                "ordering": ["-date"],
                "verbose_name": "Дневное измерение физических показателей",
                "verbose_name_plural": "Дневные измерения физических показателей",
            },
        ),
    ]
