# Generated by Django 4.1 on 2023-05-02 07:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("measurements", "0002_alter_measurecolor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnthropometryPhotoAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_access",
                    models.BooleanField(
                        default=False, verbose_name="Доступ эксперта к фото"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к фото",
                "verbose_name_plural": "Доступы к фото",
            },
        ),
        migrations.CreateModel(
            name="Anthropometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата"
                    ),
                ),
                (
                    "shoulder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Плечо",
                    ),
                ),
                (
                    "chest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Грудь",
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Талия",
                    ),
                ),
                (
                    "belly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Живот",
                    ),
                ),
                (
                    "buttocks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Ягодицы",
                    ),
                ),
                (
                    "hip",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Бедро",
                    ),
                ),
                (
                    "shin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Голень",
                    ),
                ),
                (
                    "photo_1",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="anthropometry/img/clients/%Y/%d.%m",
                        verbose_name="Фото №1",
                    ),
                ),
                (
                    "photo_2",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="anthropometry/img/clients/%Y/%d.%m",
                        verbose_name="Фото №2",
                    ),
                ),
                (
                    "photo_3",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="anthropometry/img/clients/%Y/%d.%m",
                        verbose_name="Фото №3",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Антропометрия",
                "verbose_name_plural": "Антропометрии",
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
    ]
