# Generated by Django 4.1 on 2023-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0003_anthropometryphotoaccess_anthropometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_1",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="anthropometry/img/clients/%Y/%d.%m",
                verbose_name="Фото спереди",
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_2",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="anthropometry/img/clients/%Y/%d.%m",
                verbose_name="Фото сзади",
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="photo_3",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="anthropometry/img/clients/%Y/%d.%m",
                verbose_name="Фото сбоку",
            ),
        ),
    ]
