# Generated by Django 4.2.5 on 2024-02-16 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "access",
                    models.CharField(
                        choices=[("N", "Питание"), ("T", "Тренировки"), ("F", "Полный")],
                        default="F",
                        help_text="Доступные клиенту модули приложения.",
                        max_length=1,
                        verbose_name="Доступ",
                    ),
                ),
                (
                    "default_price",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Стандартная цена подписки за месяц.",
                        verbose_name="Цена",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Тарифный план",
                "verbose_name_plural": "Тарифные планы",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Индивидуальная цена подписки за месяц. По умолчанию - стандартная цена тарифного плана.",
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата начала подписки. По умолчанию - текущая дата.",
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата окончания подписки. По умолчанию - бессрочно.",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Комментарий тоже будет виден клиенту.",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.plan",
                        verbose_name="План",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка клиента",
                "verbose_name_plural": "Подписки клиентов",
            },
        ),
    ]
