# Generated by Django 4.2.5 on 2024-02-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_plan_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="coaching",
            field=models.CharField(
                choices=[
                    ("NONE", "Нет"),
                    ("NUTRITION", "Питание"),
                    ("TRAINING", "Тренировки"),
                    ("FULL", "Полное"),
                ],
                default="NONE",
                help_text="Осуществляемое экспертом сопровождение.",
                max_length=9,
                verbose_name="Сопровождение",
            ),
        ),
    ]
