# Generated by Django 4.2.5 on 2024-02-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_plan_coaching"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="client",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="plan",
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
