# Generated by Django 4.1 on 2023-01-24 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FullClientnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='', verbose_name='Заметка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('general', models.TextField(blank=True, default='', verbose_name='Общее')),
                ('general_read', models.BooleanField(default=True, verbose_name='Общее - прочитано')),
                ('measurements', models.TextField(blank=True, default='', verbose_name='Измерения')),
                ('measurements_read', models.BooleanField(default=True, verbose_name='Измерения - прочитано')),
                ('nutrition', models.TextField(blank=True, default='', verbose_name='Питание')),
                ('nutrition_read', models.BooleanField(default=True, verbose_name='Питание - прочитано')),
                ('workout', models.TextField(blank=True, default='', verbose_name='Тренировки')),
                ('workout_read', models.BooleanField(default=True, verbose_name='Тренировки - прочитано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Clientnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('general', models.TextField(blank=True, default='', verbose_name='Общее')),
                ('measurements', models.TextField(blank=True, default='', verbose_name='Измерения')),
                ('nutrition', models.TextField(blank=True, default='', verbose_name='Питание')),
                ('workout', models.TextField(blank=True, default='', verbose_name='Тренировки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
