# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expert_remarks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientnote",
            options={
                "ordering": ["-date"],
                "verbose_name": "Заметка о клиенте помесячная",
                "verbose_name_plural": "Заметки о клиентах помесячные",
            },
        ),
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-date"],
                "verbose_name": "Комментарий от эксперта",
                "verbose_name_plural": "Комментарии от эксперта",
            },
        ),
        migrations.AlterModelOptions(
            name="fullclientnote",
            options={
                "verbose_name": "Заметка о клиенте",
                "verbose_name_plural": "Заметки о клиентах",
            },
        ),
    ]
