# Generated by Django 4.1 on 2022-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0002_rename_client_measurement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='weekday',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='День недели'),
        ),
    ]
