# Generated by Django 4.1 on 2022-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0003_measurement_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='pressure',
        ),
        migrations.AddField(
            model_name='measurement',
            name='pressure_lower',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Нижнее диастолическое давление', null=True, verbose_name='Давление нижнее'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pressure_upper',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Верхнее систолическое давление', null=True, verbose_name='Давление верхнее'),
        ),
    ]
