# Generated by Django 4.1 on 2022-08-21 13:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalpage', '0004_remove_measurement_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Дата измерения', verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата заполнения', verbose_name='Дата заполнения')),
                ('date_update', models.DateField(auto_now=True, help_text='Дата последнего редактирования', verbose_name='Дата обновления')),
                ('fullname', models.CharField(help_text='Ф. И. О. анкетируемого клиента (полностью)', max_length=100, verbose_name='Ф.И.О.')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('parameter11', models.BooleanField(verbose_name='Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке')),
                ('parameter12', models.BooleanField(verbose_name='Неприятное ощущение сильного или нерегулярного сердцебиения при нагрузке или в покое')),
                ('parameter13', models.BooleanField(verbose_name='Одышка при небольшой нагрузке или в покое')),
                ('parameter14', models.BooleanField(verbose_name='Потемнения в глазах, головокружения, обмороки, потеря равновесия')),
                ('parameter15', models.BooleanField(verbose_name='Отечность лодыжек')),
                ('parameter16', models.BooleanField(verbose_name='Чувство жжения, боль, судороги в нижних конечностях при ходьбе на малые дистанции')),
                ('parameter17', models.BooleanField(verbose_name='Другие известные клиенту причины, по которым ему следует ограничить физическую активность')),
                ('parameter20', models.BooleanField(verbose_name='В течение как минимум последних трех месяцев проводятся регулярные тренировки длительностью не менее 30 минут в день, интенсивностью не ниже умеренной, с частотой не менее трех раз в неделю')),
                ('parameter31', models.BooleanField(verbose_name='Инфаркт миокарда')),
                ('parameter32', models.BooleanField(verbose_name='Катетеризация сердца, коронарная ангиопластика, операции на сердце, трансплантация сердца')),
                ('parameter33', models.BooleanField(verbose_name='Нарушения сердечного ритма, кардиостимулятор/имплантируемый сердечный дефибриллятор')),
                ('parameter34', models.BooleanField(verbose_name='Врожденные пороки сердца, патологии сердечных клапанов, сердечная недостаточность')),
                ('parameter35', models.BooleanField(verbose_name='Сахарный диабет')),
                ('parameter36', models.BooleanField(verbose_name='Заболевания почек')),
                ('parameter41', models.CharField(max_length=100, verbose_name='Знаете ли Вы свое обычное артериальное давление? Если да, укажите его')),
                ('parameter42', models.CharField(max_length=100, verbose_name='Имеются ли у Вас изменения нормального уровня глюкозы в крови? Если да, укажите свой уровень')),
                ('parameter43', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания мочевыделительной системы? Если да, перечислите:')),
                ('parameter44', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания дыхательной системы? Если да, перечислите:')),
                ('parameter45', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания пищеварительной системы? Если да, перечислите:')),
                ('parameter46', models.CharField(max_length=255, verbose_name='Имеются ли у Вас онкологические заболевания? Если да, перечислите:')),
                ('parameter47', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания периферических сосудов? Если да, перечислите:')),
                ('parameter48', models.TextField(verbose_name='Были ли у Вас травмы и хирургические операции? Если да, то какие и когда?')),
                ('parameter49', models.CharField(max_length=255, verbose_name='Имеются ли у Вас остеопороз, проблемы со спиной и суставами? Если да, перечислите:')),
                ('parameter410', models.TextField(verbose_name='Принимаете ли Вы в настоящее время лекарства? Если да, перечислите:')),
                ('parameter411', models.CharField(max_length=100, verbose_name='Беременны ли Вы? Если да, укажите срок беременности:')),
                ('parameter412', models.CharField(max_length=255, verbose_name='Были ли у Вас роды в последние 6 месяцев? Если да, были ли осложнения до, во время и после родов? (перечислите)')),
                ('parameter413', models.TextField(verbose_name='Есть ли у Вас заболевания, не упомянутые в этой анкете? Если да, перечислите:')),
                ('parameter414', models.TextField(verbose_name='Соблюдаете ли Вы диету? Если да, то какую?')),
                ('parameter415', models.TextField(verbose_name='Были ли у Вас в прошлом занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)? Если да, то какие и когда?')),
                ('parameter416', models.TextField(verbose_name='Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)? Если да, перечислите:')),
                ('parameter416_exp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Укажите стаж занятий')),
                ('parameter416_level', models.CharField(blank=True, choices=[('low', 'меньше 2 занятий в неделю, занятия нерегулярные, нагрузки от незначительных до умеренных'), ('medium', '2–3 занятия в неделю, занятия достаточно регулярные, нагрузки от умеренных до значительных'), ('high', '3 занятий в неделю или больше, занятия регулярные, нагрузки от значительных до предельных')], max_length=10, null=True, verbose_name='Укажите привычный уровень нагрузки')),
                ('parameter417', models.CharField(max_length=255, verbose_name='Имеются ли признаки, которые позволяют заподозрить недовосстановление или перетренированность? (длительная усталость/ощущение утренней разбитости после тренировок, снижение работоспособности, раздражительность или перепады настроения, сильное нежелание тренироваться, нарушения сна) Если да, укажите их')),
                ('parameter418', models.CharField(max_length=255, verbose_name='Имеются ли особенности режима работы и отдыха, которые могут повлиять на переносимость нагрузок и восстановление после них? (сменный или ненормированный рабочий день, частые авралы на работе, невозможность полноценного сна, проблемы с регулярным питанием и пр.) Если да, укажите их')),
                ('parameter419', models.TextField(verbose_name='Имеются ли не отраженные в анкете моменты, которые могут вызвать трудности при проведении тренировок/тестов на физическую подготовленность? Если да, перечислите')),
                ('confirm', models.BooleanField(verbose_name='Подверждаю достоверность предоставленных сведений и даю согласие на обработку персональных данных')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
