# Generated by Django 4.0.6 on 2022-08-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0005_alter_measurement_date_questionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter11',
            field=models.CharField(choices=[('yes', 'да'), ('no', 'нет')], max_length=3, verbose_name='Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке'),
        ),
    ]
