# Generated by Django 4.0.6 on 2022-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0006_alter_questionary_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='parameter11',
            field=models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default='no', max_length=3, verbose_name='Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке'),
        ),
    ]
