# Generated by Django 4.0.6 on 2022-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0007_alter_questionary_parameter11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='parameter11',
            field=models.BooleanField(choices=[('1', 'да'), ('0', 'нет')], default='0', verbose_name='Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке'),
        ),
    ]
