# Generated by Django 4.0.6 on 2022-08-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0008_alter_questionary_parameter11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='parameter12',
            field=models.BooleanField(choices=[('1', 'да'), ('0', 'нет')], default='0', verbose_name='Неприятное ощущение сильного или нерегулярного сердцебиения при нагрузке или в покое'),
        ),
    ]
