# Generated by Django 4.0.6 on 2022-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0011_alter_questionary_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='parameter15',
            field=models.BooleanField(choices=[('1', 'да '), ('0', 'нет')], verbose_name='Отечность лодыжек'),
        ),
    ]
