# Generated by Django 4.0.6 on 2022-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0012_alter_questionary_parameter15'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionary',
            old_name='parameter41',
            new_name='norm_pressure',
        ),
        migrations.AlterField(
            model_name='questionary',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter15',
            field=models.BooleanField(choices=[('1', 'да '), ('0', 'нет')], default='0', verbose_name='Отечность лодыжек'),
        ),
    ]
