# Generated by Django 4.0.6 on 2022-08-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0013_rename_parameter41_questionary_norm_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionary',
            name='parameter416_level',
        ),
        migrations.AlterField(
            model_name='questionary',
            name='norm_pressure',
            field=models.CharField(max_length=100, verbose_name='Знаете ли Вы свое обычное артериальное давление?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter410',
            field=models.TextField(verbose_name='Принимаете ли Вы в настоящее время лекарства?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter411',
            field=models.CharField(max_length=100, verbose_name='Беременны ли Вы?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter412',
            field=models.CharField(max_length=255, verbose_name='Были ли у Вас роды в последние 6 месяцев?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter413',
            field=models.TextField(verbose_name='Есть ли у Вас заболевания, не упомянутые в этой анкете?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter414',
            field=models.TextField(verbose_name='Соблюдаете ли Вы диету?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter415',
            field=models.TextField(verbose_name='Были ли у Вас в прошлом занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter416',
            field=models.CharField(choices=[('low', 'меньше 2 занятий в неделю, занятия нерегулярные, нагрузки от незначительных до умеренных'), ('medium', '2–3 занятия в неделю, занятия достаточно регулярные, нагрузки от умеренных до значительных'), ('high', '3 занятий в неделю или больше, занятия регулярные, нагрузки от значительных до предельных'), ('no', 'нет')], max_length=6, verbose_name='Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter42',
            field=models.CharField(max_length=100, verbose_name='Имеются ли у Вас изменения нормального уровня глюкозы в крови?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter43',
            field=models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания мочевыделительной системы?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter44',
            field=models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания дыхательной системы?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter45',
            field=models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания пищеварительной системы?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter46',
            field=models.CharField(max_length=255, verbose_name='Имеются ли у Вас онкологические заболевания?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter47',
            field=models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания периферических сосудов?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter48',
            field=models.TextField(verbose_name='Были ли у Вас травмы и хирургические операции?'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter49',
            field=models.CharField(max_length=255, verbose_name='Имеются ли у Вас остеопороз, проблемы со спиной и суставами?'),
        ),
    ]
