# Generated by Django 4.0.6 on 2022-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0014_remove_questionary_parameter416_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionary',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='norm_pressure',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter410',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter411',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter412',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter413',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter414',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter415',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter416',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter416_exp',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter417',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter418',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter419',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter42',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter43',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter44',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter45',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter46',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter47',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter48',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='parameter49',
        ),
        migrations.AlterField(
            model_name='questionary',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name='Фамилия Имя Отчество'),
        ),
    ]
