# Generated by Django 4.0.6 on 2022-08-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0018_questionary_norm_pressure_questionary_parameter410_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='parameter416',
            field=models.CharField(default=1, max_length=6, verbose_name='Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionary',
            name='parameter416_exp',
            field=models.CharField(default='', max_length=200, verbose_name='Укажите стаж занятий'),
        ),
    ]
