# Generated by Django 4.0.6 on 2022-08-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0019_questionary_parameter416_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Подверждаю достоверность предоставленных сведений и даю согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='questionary',
            name='parameter417',
            field=models.CharField(default=1, max_length=255, verbose_name='Имеются ли признаки, которые позволяют заподозрить недовосстановление или перетренированность? (длительная усталость/ощущение утренней разбитости после тренировок, снижение работоспособности, раздражительность или перепады настроения, сильное нежелание тренироваться, нарушения сна)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionary',
            name='parameter418',
            field=models.CharField(default=1, max_length=255, verbose_name='Имеются ли особенности режима работы и отдыха, которые могут повлиять на переносимость нагрузок и восстановление после них? (сменный или ненормированный рабочий день, частые авралы на работе, невозможность полноценного сна, проблемы с регулярным питанием и пр.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionary',
            name='parameter419',
            field=models.TextField(default=1, verbose_name='Имеются ли не отраженные в анкете моменты, которые могут вызвать трудности при проведении тренировок/тестов на физическую подготовленность?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionary',
            name='parameter416_exp',
            field=models.CharField(default='', max_length=200, verbose_name='Cтаж занятий'),
        ),
    ]
