# Generated by Django 4.1 on 2022-08-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0021_fatsecretentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatsecretentry',
            name='session_token',
        ),
    ]
