# Generated by Django 4.1 on 2022-08-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0022_remove_fatsecretentry_session_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название продукта')),
                ('product_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('product_calories', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Калории')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalpage.measurement')),
            ],
        ),
    ]
