# Generated by Django 4.1 on 2022-08-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0023_eatenproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatenproduct',
            name='product_metric',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения'),
        ),
    ]
