# Generated by Django 4.1 on 2022-09-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0024_eatenproduct_product_metric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EatenProduct',
        ),
    ]
