# Generated by Django 4.1 on 2022-09-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0025_delete_eatenproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='weekday',
        ),
    ]
