# Generated by Django 4.1 on 2022-09-06 10:47

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalpage', '0026_remove_measurement_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anthropometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='Дата измерения', verbose_name='Дата')),
                ('shoulder', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Плечо')),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Грудь')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Талия')),
                ('belly', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Живот')),
                ('buttocks', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Ягодицы')),
                ('hip', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Бедро')),
                ('shin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Голень')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
