# Generated by Django 4.1 on 2022-09-07 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0027_anthropometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometry',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата измерения'),
        ),
    ]
