# Generated by Django 4.1 on 2022-09-07 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0028_alter_anthropometry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anthropometry',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='anthropometry',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
