# Generated by Django 4.1 on 2022-09-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0029_alter_anthropometry_options_alter_anthropometry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthropometry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/personalpage/img', verbose_name='Фото'),
        ),
    ]
