# Generated by Django 4.1 on 2022-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0031_alter_anthropometry_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthropometry',
            name='photo',
        ),
        migrations.AddField(
            model_name='anthropometry',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='personalpage/img/clients/%Y/%d.%m', verbose_name='Фото №1'),
        ),
        migrations.AddField(
            model_name='anthropometry',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='personalpage/img/clients/%Y/%d.%m', verbose_name='Фото №2'),
        ),
        migrations.AddField(
            model_name='anthropometry',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='personalpage/img/clients/%Y/%d.%m', verbose_name='Фото №3'),
        ),
    ]
