# Generated by Django 4.1 on 2022-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0033_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#FF0000', max_length=20, verbose_name='Цвет фона')),
            ],
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='photo_access',
            field=models.BooleanField(default=False, verbose_name='Доступ эксперта к фото'),
        ),
    ]
