# Generated by Django 4.1 on 2022-11-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0034_measurecolor_alter_usersettings_photo_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurecolor',
            name='color',
            field=models.CharField(default='#ffffff00', max_length=20, verbose_name='Цвет фона'),
        ),
    ]
