# Generated by Django 4.1 on 2022-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0035_alter_measurecolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurecolor',
            name='meaning',
            field=models.CharField(default='', max_length=100, verbose_name='Значение фона'),
        ),
    ]
