# Generated by Django 4.1 on 2022-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0037_alter_measurecolor_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurecolor',
            name='meaning',
            field=models.CharField(max_length=100, verbose_name='Значение фона'),
        ),
    ]
