# Generated by Django 4.1 on 2022-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0038_alter_measurecolor_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50, verbose_name='Показатель здоровья')),
            ],
        ),
    ]
