# Generated by Django 4.1 on 2022-11-13 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalpage', '0039_measureindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureColorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_limit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Нижняя граница включительно')),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Верхняя граница включительно')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalpage.measurecolor')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalpage.measureindex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
