# Generated by Django 4.1 on 2022-11-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0040_measurecolorfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurecolorfield',
            name='color',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='personalpage.measurecolor'),
        ),
    ]
