# Generated by Django 4.1 on 2022-11-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0041_alter_measurecolorfield_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurecolorfield',
            name='low_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Нижняя граница включительно'),
        ),
        migrations.AlterField(
            model_name='measurecolorfield',
            name='upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Верхняя граница включительно'),
        ),
    ]
