# Generated by Django 4.1 on 2022-11-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0043_rename_index_measureindex_index_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurecolorfield',
            name='low_limit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Нижняя граница включительно'),
        ),
        migrations.AlterField(
            model_name='measurecolorfield',
            name='upper_limit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Верхняя граница включительно'),
        ),
    ]
