# Generated by Django 4.1 on 2023-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0051_alter_usersettings_preferred_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureindex',
            name='index_name',
            field=models.CharField(max_length=50, verbose_name='Показатель'),
        ),
    ]
