# Generated by Django 4.1 on 2023-01-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0052_alter_measureindex_index_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurecolorfield',
            name='color',
        ),
        migrations.RemoveField(
            model_name='measurecolorfield',
            name='index',
        ),
        migrations.RemoveField(
            model_name='measurecolorfield',
            name='user',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='user',
        ),
        migrations.DeleteModel(
            name='MeasureColor',
        ),
        migrations.DeleteModel(
            name='MeasureColorField',
        ),
        migrations.DeleteModel(
            name='MeasureIndex',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
