# Generated by Django 4.1 on 2023-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0053_remove_measurecolorfield_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FatSecretEntry',
        ),
    ]
