# Generated by Django 4.1 on 2023-01-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0054_delete_fatsecretentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='photo_access',
        ),
        migrations.DeleteModel(
            name='Anthropometry',
        ),
    ]
