# Generated by Django 4.1 on 2023-01-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpage', '0055_remove_usersettings_photo_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Questionary',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
