# Generated by Django 4.1 on 2023-01-23 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthQuestionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата заполнения', verbose_name='Дата заполнения')),
                ('date_update', models.DateField(auto_now=True, help_text='Дата последнего редактирования', verbose_name='Дата обновления')),
                ('fullname', models.CharField(max_length=200, verbose_name='Фамилия Имя Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('parameter12', models.CharField(max_length=3, verbose_name='Неприятное ощущение сильного или нерегулярного сердцебиения при нагрузке или в покое')),
                ('parameter13', models.CharField(max_length=3, verbose_name='Одышка при небольшой нагрузке или в покое')),
                ('parameter14', models.CharField(max_length=3, verbose_name='Потемнения в глазах, головокружения, обмороки, потеря равновесия')),
                ('parameter11', models.CharField(max_length=3, verbose_name='Дискомфорт или боли в груди при нагрузке или в покое; боль в левой половине нижней челюсти, шеи, левой руке')),
                ('parameter15', models.CharField(max_length=3, verbose_name='Отечность лодыжек')),
                ('parameter16', models.CharField(max_length=3, verbose_name='Чувство жжения, боль, судороги в нижних конечностях при ходьбе на малые дистанции')),
                ('parameter17', models.CharField(max_length=3, verbose_name='Другие известные клиенту причины, по которым ему следует ограничить физическую активность')),
                ('parameter20', models.CharField(max_length=3, verbose_name='В течение как минимум последних трех месяцев проводятся регулярные тренировки длительностью не менее 30 минут в день, интенсивностью не ниже умеренной, с частотой не менее трех раз в неделю')),
                ('parameter31', models.CharField(max_length=3, verbose_name='Инфаркт миокарда')),
                ('parameter32', models.CharField(max_length=3, verbose_name='Катетеризация сердца, коронарная ангиопластика, операции на сердце, трансплантация сердца')),
                ('parameter33', models.CharField(max_length=3, verbose_name='Нарушения сердечного ритма, кардиостимулятор/имплантируемый сердечный дефибриллятор')),
                ('parameter34', models.CharField(max_length=3, verbose_name='Врожденные пороки сердца, патологии сердечных клапанов, сердечная недостаточность')),
                ('parameter35', models.CharField(max_length=3, verbose_name='Сахарный диабет')),
                ('parameter36', models.CharField(max_length=3, verbose_name='Заболевания почек')),
                ('norm_pressure', models.CharField(max_length=100, verbose_name='Знаете ли Вы свое обычное артериальное давление?')),
                ('parameter42', models.CharField(max_length=100, verbose_name='Имеются ли у Вас изменения нормального уровня глюкозы в крови?')),
                ('parameter43', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания мочевыделительной системы?')),
                ('parameter44', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания дыхательной системы?')),
                ('parameter45', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания пищеварительной системы?')),
                ('parameter46', models.CharField(max_length=255, verbose_name='Имеются ли у Вас онкологические заболевания?')),
                ('parameter47', models.CharField(max_length=255, verbose_name='Имеются ли у Вас заболевания периферических сосудов?')),
                ('parameter48', models.TextField(verbose_name='Были ли у Вас травмы и хирургические операции?')),
                ('parameter49', models.CharField(max_length=255, verbose_name='Имеются ли у Вас остеопороз, проблемы со спиной и суставами?')),
                ('parameter410', models.TextField(verbose_name='Принимаете ли Вы в настоящее время лекарства?')),
                ('parameter411', models.CharField(max_length=100, verbose_name='Беременны ли Вы?')),
                ('parameter412', models.CharField(max_length=255, verbose_name='Были ли у Вас роды в последние 6 месяцев?')),
                ('parameter413', models.TextField(verbose_name='Есть ли у Вас заболевания, не упомянутые в этой анкете?')),
                ('parameter414', models.TextField(verbose_name='Соблюдаете ли Вы диету?')),
                ('parameter415', models.TextField(verbose_name='Были ли у Вас в прошлом занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)?')),
                ('parameter416', models.CharField(max_length=6, verbose_name='Есть ли у Вас в настоящее время занятия, связанные с двигательной активностью (спорт, фитнес, танцы, йога и пр.)?')),
                ('parameter416_exp', models.CharField(default='', max_length=200, verbose_name='Cтаж занятий')),
                ('parameter417', models.CharField(max_length=255, verbose_name='Имеются ли признаки, которые позволяют заподозрить недовосстановление или перетренированность? (длительная усталость/ощущение утренней разбитости после тренировок, снижение работоспособности, раздражительность или перепады настроения, сильное нежелание тренироваться, нарушения сна)')),
                ('parameter418', models.CharField(max_length=255, verbose_name='Имеются ли особенности режима работы и отдыха, которые могут повлиять на переносимость нагрузок и восстановление после них? (сменный или ненормированный рабочий день, частые авралы на работе, невозможность полноценного сна, проблемы с регулярным питанием и пр.)')),
                ('parameter419', models.TextField(verbose_name='Имеются ли не отраженные в анкете моменты, которые могут вызвать трудности при проведении тренировок/тестов на физическую подготовленность?')),
                ('confirm', models.BooleanField(default=False, verbose_name='Подверждаю достоверность предоставленных сведений и даю согласие на обработку персональных данных')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(blank=True, max_length=250, null=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, max_length=250, null=True, verbose_name='Whatsapp')),
                ('discord', models.URLField(blank=True, max_length=250, null=True, verbose_name='Discord')),
                ('skype', models.URLField(blank=True, max_length=250, null=True, verbose_name='Skype')),
                ('vkontakte', models.URLField(blank=True, max_length=250, null=True, verbose_name='Vkontakte')),
                ('facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name='Facebook')),
                ('preferred_contact', models.CharField(choices=[('TG', 'Telegram'), ('WA', 'Whatsapp'), ('DC', 'Discord'), ('SK', 'Skype'), ('VK', 'Vkontakte'), ('FB', 'Facebook'), ('No', 'не выбрано')], default='No', max_length=2, verbose_name='Предпочтительный способ связи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
