# Generated by Django 4.1 on 2023-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthquestionary',
            name='parameter416_exp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cтаж занятий'),
        ),
    ]
