# Generated by Django 4.1 on 2023-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_info', '0005_alter_healthquestionary_parameter416_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='discord',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Discord'),
        ),
    ]
