# Generated by Django 4.1 on 2023-02-18 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_info', '0006_alter_clientcontact_discord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetQuestionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата заполнения', verbose_name='Дата заполнения')),
                ('date_update', models.DateField(auto_now=True, help_text='Дата последнего редактирования', verbose_name='Дата обновления')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('?', 'Другой')], max_length=1, verbose_name='Биологический пол')),
                ('sex_comment', models.TextField(blank=True, default='', verbose_name='Прокоментируйте свой ответ')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Текущий вес')),
                ('weight_min', models.PositiveSmallIntegerField(verbose_name='Минимальный вес за последние 5 лет')),
                ('weight_max', models.PositiveSmallIntegerField(verbose_name='Максимальный вес за последние 5 лет')),
                ('weight_avg', models.PositiveSmallIntegerField(blank=True, help_text='указывать, если сейчас 30 лет и более', null=True, verbose_name='Средний вес между 20-25 годами')),
                ('daily_steps', models.CharField(max_length=255, verbose_name='Среднее количество шагов в сутки')),
                ('daily_meals_amount', models.CharField(max_length=255, verbose_name='Количество полноценных приёмов пищи в сутки')),
                ('daily_snacks_amount', models.CharField(max_length=255, verbose_name='Количество перекусов в сутки')),
                ('daily_meal', models.TextField(verbose_name='Перечислите пищу, которую вы едите каждый день')),
                ('weekly_meal', models.TextField(verbose_name='Перечислите пищу, которую вы едите каждую неделю')),
                ('goal', models.TextField(verbose_name='Ваша цель')),
                ('goal_mark', models.TextField(verbose_name='Какой показатель поможет нам эту цель измерить? (например, килограммы)')),
                ('goal_attempts', models.TextField(verbose_name='Были ли ранее попытки достичь этой цели? Опишите их и назовите количество')),
                ('goal_obstacle', models.TextField(verbose_name='Главные препятствия к достижению вашей цели')),
                ('goal_importance', models.PositiveSmallIntegerField(verbose_name='Насколько важна указанная цель')),
                ('goal_maxtime', models.TextField(verbose_name='Какое максимальное количество времени можно уделить достижению цели')),
                ('readiness_to_change', models.CharField(choices=[('1', 'Не вижу необходимости в серьёзных переменах, хочу лишь слегка скорректировать образ жизни.'), ('2', 'Готов к переменам в образе жизни, скоро начну их воплощать.'), ('3', 'Хочу изменить свой образ жизни, но не уверен, что смогу.'), ('4', 'Начал менять образ жизни в течение последнего полугода.'), ('5', 'Работаю над изменением образа жизни, но чувствую, что нуждаюсь в помощи, чтобы продвинуться дальше.'), ('6', 'Активно работаю над собой, продвигаюсь, но хочу делать это ещё лучше.')], max_length=1, verbose_name='Готовность к изменениям')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
