# Generated by Django 4.1 on 2023-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_info', '0008_alter_meetquestionary_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetquestionary',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('?', 'Другой'), ('', '')], max_length=1, verbose_name='Биологический пол'),
        ),
    ]
