# Generated by Django 4.1 on 2023-02-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_info', '0009_alter_meetquestionary_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetquestionary',
            name='sleep_problems',
            field=models.TextField(blank=True, default='', verbose_name='Как часто нарушается и на какое время'),
        ),
        migrations.AddField(
            model_name='meetquestionary',
            name='sleep_time',
            field=models.CharField(default=111, max_length=255, verbose_name='Время укладывания ко сну'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetquestionary',
            name='wakeup_time',
            field=models.CharField(default='abc', max_length=255, verbose_name='Время вставания после сна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetquestionary',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('?', 'Другой')], max_length=1, verbose_name='Биологический пол'),
        ),
        migrations.AlterField(
            model_name='meetquestionary',
            name='sex_comment',
            field=models.TextField(blank=True, default='', verbose_name='Прокомментируйте свой ответ'),
        ),
        migrations.AlterField(
            model_name='meetquestionary',
            name='weight_avg',
            field=models.PositiveSmallIntegerField(blank=True, help_text='указывайте, если вам сейчас 30 лет и более', null=True, verbose_name='Средний вес между 20-25 годами'),
        ),
    ]
