# Generated by Django 4.1 on 2023-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_info', '0011_remove_meetquestionary_daily_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetquestionary',
            name='common_meal',
            field=models.TextField(verbose_name='5 видов пищи, которую вы едите наиболее часто и регулярно'),
        ),
        migrations.AlterField(
            model_name='meetquestionary',
            name='favorite_meal',
            field=models.TextField(verbose_name='5 видов пищи, которую вы считаете самой вкусной, желанной и любимой'),
        ),
        migrations.AlterField(
            model_name='meetquestionary',
            name='weekly_meal',
            field=models.TextField(verbose_name='5 видов пищи, которую вы едите примерно раз в неделю'),
        ),
        migrations.AlterField(
            model_name='meetquestionary',
            name='yearly_meal',
            field=models.TextField(verbose_name='5 видов пищи, которую вы едите несколько раз в год'),
        ),
    ]
