# Generated by Django 4.1 on 2023-02-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_info', '0012_alter_meetquestionary_common_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(blank=True, default='', verbose_name='Общее')),
                ('measurements', models.TextField(blank=True, default='', verbose_name='Измерения')),
                ('nutrition', models.TextField(blank=True, default='', verbose_name='Питание')),
                ('workout', models.TextField(blank=True, default='', verbose_name='Тренировки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
