# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_info", "0013_clientmemo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientcontact",
            options={
                "verbose_name": "Контакты клиента",
                "verbose_name_plural": "Контакты клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="clientmemo",
            options={
                "verbose_name": "Личная заметка клиента",
                "verbose_name_plural": "Личные заметки клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="healthquestionary",
            options={
                "verbose_name": "Анкета здоровья клиента",
                "verbose_name_plural": "Анкеты здоровья клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="meetquestionary",
            options={
                "verbose_name": "Анкета знакомства клиента",
                "verbose_name_plural": "Анкеты знакомства клиентов",
            },
        ),
    ]
