# Generated by Django 4.1 on 2023-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заполнения заявки')),
                ('name', models.CharField(help_text='Как к вам обращаться?', max_length=100, verbose_name='Имя')),
                ('age', models.CharField(blank=True, help_text='Сколько вам лет?', max_length=100, verbose_name='Возраст')),
                ('location', models.CharField(blank=True, help_text='Расскажите, откуда вы?', max_length=100, verbose_name='Место жительства')),
                ('email', models.EmailField(blank=True, help_text='Обещаем не использовать адрес в коварных целях!', max_length=100, verbose_name='Почта')),
                ('contacts', models.CharField(help_text='Оставьте ссылку на предпочитаемый способ связи', max_length=255, verbose_name='Контакты')),
                ('is_read', models.BooleanField(default=False, verbose_name='Заявка прочитана')),
                ('expert_note', models.TextField(blank=True, default='', verbose_name='Заметка')),
            ],
        ),
    ]
