# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultation_signup", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultationsignup",
            options={
                "verbose_name": "Заявка на консультацию",
                "verbose_name_plural": "Заявки на консультацию",
            },
        ),
    ]
