# Generated by Django 4.1 on 2023-03-25 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "Power"), ("E", "Endurance")],
                        default="P",
                        max_length=1,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="training/img/exercise_icons/",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "effect_area",
                    models.JSONField(
                        default=list,
                        verbose_name="Список областей воздействия",
                    ),
                ),
                (
                    "video",
                    models.URLField(
                        blank=True, null=True, verbose_name="Видео"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата тренировки")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("P", "Power"),
                            ("PR", "PowerRound"),
                            ("E", "Endurance"),
                            ("EI", "EnduranceInterval"),
                        ],
                        max_length=2,
                        verbose_name="Тип тренировки",
                    ),
                ),
                (
                    "tiredness_due",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Утомление (запланировано)",
                    ),
                ),
                (
                    "tiredness_get",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Утомление (получено)",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Длительность в минутах",
                    ),
                ),
                (
                    "pulse_avg",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Пульс в среднем"
                    ),
                ),
                (
                    "pulse_max",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Пульс максимальный",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PowerExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approaches_due",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Подходы (запланировано)",
                    ),
                ),
                (
                    "approaches_made",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Подходы (выполнено)",
                    ),
                ),
                (
                    "repeats_due",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Повторы (запланировано)",
                    ),
                ),
                (
                    "repeats_made",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Повторы (выполнено)",
                    ),
                ),
                (
                    "load_due",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Нагрузка (запланировано)",
                    ),
                ),
                (
                    "load_get",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Нагрузка (получено)",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False, verbose_name="Упражнение выполнено"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.exercise",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.training",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="intervalExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "high_load_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Время на высокой нагрузке в минутах",
                    ),
                ),
                (
                    "high_load_pulse",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Пульс на высокой нагрузке",
                    ),
                ),
                (
                    "low_load_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Время на низкой нагрузке в минутах",
                    ),
                ),
                (
                    "low_load_pulse",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Пульс на низкой нагрузке",
                    ),
                ),
                (
                    "repeats",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Повторы цикла"
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False, verbose_name="Упражнение выполнено"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.exercise",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.training",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnduranceExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Длительность в минутах",
                    ),
                ),
                (
                    "pulse_avg",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Пульс в среднем"
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False, verbose_name="Упражнение выполнено"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.exercise",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.training",
                    ),
                ),
            ],
        ),
    ]
