# Generated by Django 4.2.5 on 2023-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exerciserecord",
            options={
                "ordering": ("order", "pk"),
                "verbose_name": "Запись о выполнении упражнения",
                "verbose_name_plural": "Записи о выполнении упражнений",
            },
        ),
        migrations.AddField(
            model_name="exerciserecord",
            name="order",
            field=models.SmallIntegerField(default=1, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="training/exercise/images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="training/exercise/images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="exerciserecord",
            name="high_load_time",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Время при высокой нагрузке"
            ),
        ),
        migrations.AlterField(
            model_name="exerciserecord",
            name="is_done",
            field=models.BooleanField(default=False, verbose_name="Выполнено"),
        ),
        migrations.AlterField(
            model_name="exerciserecord",
            name="low_load_time",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Время при низкой нагрузке"
            ),
        ),
        migrations.AlterField(
            model_name="exerciserecord",
            name="pulse_avg",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Средний пульс"
            ),
        ),
        migrations.AlterField(
            model_name="exerciserecord",
            name="time",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Длительность"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="pulse_avg",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Средний пульс"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="pulse_max",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Макс пульс"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="time",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Длительность"
            ),
        ),
    ]
