# Generated by Django 4.1 on 2023-03-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0002_alter_training_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerexercise",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Вес в килограммах",
            ),
        ),
    ]
