# Generated by Django 4.1 on 2023-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0004_alter_training_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="effect_area",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Список областей воздействия",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                choices=[("P", "Сила"), ("E", "Выносливость")],
                default="P",
                max_length=1,
                verbose_name="Тип",
            ),
        ),
    ]
