# Generated by Django 4.1 on 2023-03-28 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0005_alter_exercise_effect_area_alter_exercise_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="effect_area",
            new_name="effect_areas",
        ),
    ]
