# Generated by Django 4.1 on 2023-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0006_rename_effect_area_exercise_effect_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="mistakes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Возможные ошибки выполнения",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="photo_init_pose",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="training/img/exercise_photos/",
                verbose_name="Исходное положение",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="photo_work_pose",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="training/img/exercise_photos/",
                verbose_name="Рабочее положение",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_muscles",
            field=models.TextField(
                blank=True, null=True, verbose_name="Целевые мышцы"
            ),
        ),
    ]
