# Generated by Django 4.1 on 2023-04-01 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "training",
            "0009_rename_enduranceexercise_enduranceexercisereport_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="type",
            new_name="exercise_type",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="type",
            new_name="exercise_type",
        ),
    ]
