# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0012_exercisereport_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Упражнения",
            },
        ),
        migrations.AlterModelOptions(
            name="exercisereport",
            options={
                "verbose_name": "Отчет об упражнении",
                "verbose_name_plural": "Отчеты об упражнениях",
            },
        ),
        migrations.AlterModelOptions(
            name="training",
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
            },
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="photo_init_pose",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="photo_work_pose",
        ),
        migrations.AddField(
            model_name="exercise",
            name="photo_1",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="training/img/exercise_photos/",
                verbose_name="Фото или гифка",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="photo_2",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="training/img/exercise_photos/",
                verbose_name="Фото или гифка",
            ),
        ),
    ]
