# Generated by Django 4.1 on 2023-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "training",
            "0013_alter_exercise_options_alter_exercisereport_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="mistakes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Основные ошибки выполнения",
            ),
        ),
    ]
